# Py-Numeric-Computing Assignment Answers

## Part 1: Array Slicing and Indexing

In [4]:
import numpy as np

##### 2. Given a 1D numpy array x, write the syntax used to return only the odd-indexed entries (return every other entry) of x. There is more than one solution!

In [6]:
x = np.arange(10)
y = x[x % 2 != 0]
y

array([1, 3, 5, 7, 9])

##### 3. Given an integer numpy array of 0's and 1's, write a function that creates a new array where 0's are replaced with the word "red" and 1's are replaced with the word "blue".

In [7]:
x = np.array([0, 0, 1, 0, 1]) 

def color_replace(x):
    return np.where(x == 0, "red", "blue")

color_replace(x)

array(['red', 'red', 'blue', 'red', 'blue'], dtype='<U4')

##### 4. Given a square numpy array X, write a function that replaces the diagonal elements with a given constant. Hint: you can use ONE for loop in this function!

In [8]:

x = np.random.randint(1, 11, size=(6, 6))
x

array([[ 6,  6, 10,  4,  8,  8],
       [ 2,  1,  6,  9, 10, 10],
       [ 1,  9,  7,  9,  9,  1],
       [ 4,  4,  6,  4, 10,  2],
       [ 9,  8,  6,  6,  7,  4],
       [ 2,  4, 10,  5,  6,  8]])

In [9]:

def diagonal_replace(x):
    y = np.fill_diagonal(x, 0)
    return x

diagonal_replace(x)

array([[ 0,  6, 10,  4,  8,  8],
       [ 2,  0,  6,  9, 10, 10],
       [ 1,  9,  0,  9,  9,  1],
       [ 4,  4,  6,  0, 10,  2],
       [ 9,  8,  6,  6,  0,  4],
       [ 2,  4, 10,  5,  6,  0]])

##### 5. Given two equal length arrays, x with some general numeric data, and b an array of booleans, write a function that computes the sum of the data in x at the same positions where b is True, and the sum of the values in x at the positions where b is False.

In [10]:

x = np.array([0,    1,    2,     3,    4,     5])
b = np.array([True, True, False, True, False, False])

def compute_true_false_sums(x, b):
    return "True: " + str(sum(x[b])) +" , False: " + str(sum(x[np.invert(b)]))
    
compute_true_false_sums(x, b)

'True: 4 , False: 11'

#### 6. Given a two-dimensional array M, create a new two-dimensional array containing only the columns of M where at least one of the entries is negative.

In [11]:

M = np.array([[ 0.5,  0.2, -0.3,  0. ],
              [ 0.4,  0.3,  0.3,  0.4],
              [-0.2, -0.4,  0.1,  0.4]])

def select_negative_columns(M):
    return M[:, (M < 0).any(axis=0)]

select_negative_columns(M)

array([[ 0.5,  0.2, -0.3],
       [ 0.4,  0.3,  0.3],
       [-0.2, -0.4,  0.1]])

## Part 2: Applying Operations

In [14]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 1. Take the natural log of the entire array a.

In [15]:
np.log(a[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

##### 2. Compute the cumulative sum of array a.

In [16]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

##### 3. Write a function that consumes a two-dimensional numpy array (so, a matrix), and a label which is either "row" or "column". The function should return a one-dimensional numpy array (vector) with either the row or column averages.

In [17]:
x = np.array([[0, 1], [2, 1]])


def row_or_column_means(x,label):
    label = input('Input "column" or "row": ')
    if label == "column":
        return np.mean(x, axis=1)
    elif label == "row":
        return np.mean(x, axis=0)
    else:
        return "incompatible input"

row_or_column_means(x, "column")

Input "column" or "row": column


array([0.5, 1.5])

##### 4. Subtract the row mean from each row of a two-dimensional array (element by element).

In [18]:
x = np.array([[0, 1, 0, 1], [1, 1, 1, 1], [1, 2, 3, 4]])

def subtract_row_means(x):
    column_vector = np.mean(x, axis = 1).reshape(3,1)
    return x - column_vector

subtract_row_means(x)

array([[-0.5,  0.5, -0.5,  0.5],
       [ 0. ,  0. ,  0. ,  0. ],
       [-1.5, -0.5,  0.5,  1.5]])

## Part 3: Broadcasting

##### 1. Same size broadcasting: start with arrays x and y. Compute the element-wise: sum, difference, product, division, and modular division of x and y.

In [20]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([2, 4, 6, 8, 10, 12])

In [21]:
x + y

array([ 3,  6,  9, 12, 15, 18])

In [22]:

x - y

array([-1, -2, -3, -4, -5, -6])

In [23]:

x * y


array([ 2,  8, 18, 32, 50, 72])

In [24]:
x / y

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [25]:
x % y

array([1, 2, 3, 4, 5, 6], dtype=int32)

##### 2. Single digit broadcasting: continue using array y defined above. Compute the element-wise: sum, difference, product, division, and modular division of y and 2.

In [26]:
y + 2

array([ 4,  6,  8, 10, 12, 14])

In [27]:
y - 2

array([ 0,  2,  4,  6,  8, 10])

In [28]:
y * 2

array([ 4,  8, 12, 16, 20, 24])

In [29]:
y / 2

array([1., 2., 3., 4., 5., 6.])

In [30]:
y % 2

array([0, 0, 0, 0, 0, 0], dtype=int32)

##### 3. Broadcasting conditionals: Continue using arrays x and y defined above. Use conditional statements to get an elementwise boolean array for:
###### elements of y that are greater than 5

In [31]:
y > 5

array([False, False,  True,  True,  True,  True])

###### elements of x that are divisible by 2 (hint: modular division by 2 leaves 0 remainder

In [32]:
x % 2 == 0

array([False,  True, False,  True, False,  True])

##### 4. Broadcasting in multiple dimensions: Let's start with a new array x,

In [33]:
x = np.ones((5, 4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##### Try a broadcasting operation (e.g. multiplication) with x and array a = np.array([1, 2, 3, 4]).

In [34]:
a = np.array([1,2,3,4])
x * a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])